[build]
command = "npm run build" # Adjust the build command as needed
publish = "uploads"       # Specify the publish directory as "uploads"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

# Add this section to specify the "uploads" directory
[[redirects]]
force = true
from = "/uploads/*"
status = 200
to = "/uploads/:splat"
